### PR TITLE
Skip exceptions

### PR DESCRIPTION
**Pull request by moebiuseye**
A few additions related to what was said on comments to pull request #399

### CODE REVIEW

**Comment by moebiuseye** [comment]
This build is working fine. 

https://travis-ci.org/moebiuseye/salt-winrepo-ng/builds/136654743

**Comment by TheBigBear** [comment]
@moebiuseye thanks for this. looks very good. I like it. any chance you could separate out (or remove) the changes to unrelated softwares? (duplicati.sls can stay, but miktex-basic, salt-minion and wireshark really should not be part of this PR merge.)

**Comment by TheBigBear** [comment]
@moebiuseye ok, just switched my brain on. ;-) looks like the miktex-basic salt-minion and wireshark changes were likely done by you to get travis ci to pass. ;-) will fix those in main branch and your PR should merge in cleanly after that. ;-) hold fire on changing this patch for now. ;-)

**Comment by TheBigBear** [comment]
@moebiuseye if you rebase your work now, you should be good to go. 

git pull --rebase upstream master
git pull 
git  push

PS: 
obviously need the remote 'upstream' setup and pointed to the main saltstack repo upstream from your own fork

**Comment by TheBigBear** [comment]
@moebiuseye great work. @UtahDave ^^ from saltstack noticed this and asked me to pass on his thanks and regards.

**Comment by UtahDave** [comment]
@moebiuseye Thanks for the good work on this! Testing is always something we're trying to improve on.

**Comment by moebiuseye** [comment]
Thank you @UtahDave I'm a fan of saltstack! You guy rock. :+1:

**Pull request merged**
