### PR TITLE
Update url rewrite

### PR DESCRIPTION
**Pull request by keslerm**

### CODE REVIEW

**Comment by keslerm** [comment]
It looks like MS pulled the 7.2.1952 installers down.

**Comment by TheBigBear** [comment]
@keslerm  I have updated urlrewrite to latest and archived old releases in such a way that they can still be listed and / or uninstalled. Had to get msi product GUID for that, so the uninstall works without having the msi to hand. 
[ see https://github.com/saltstack/salt-winrepo-ng/pull/1823 ]

**Comment by TheBigBear** [comment]
@keslerm winrepo-ng dos not want to drop off or simply removed old or no longer available pkg release as they would risk to become stuck in an install. They want the old ones to still be listable and if at all possible uninstallable.

**Comment by keslerm** [comment]
@TheBigBear looks good i'll close this one

**Pull request closed without merging**
