### PR TITLE
fix typo on first line of evernote definition

### PR DESCRIPTION
**Pull request by vernondcole**
Unfortunately, I cannot test this due to the "feature" that one cannot override the default for "winrepo_remotes_ng".  We need to re-open that issue, I think.

### CODE REVIEW

**Comment by vernondcole** [comment]
@TheBigBear please review this.

**Comment by TheBigBear** [comment]
@vernondcole so sorry about this. More 'haste' less speed ... ;-)

**Comment by vernondcole** [comment]
Thanks for the quick work.  I discovered last night why I could not switch
to my fork to test my fix.  It is a design error, but they swept it under
the rug three years ago with a documentation change telling us how we can
not use the facility at all.  Not the correct answer. I think I will
re-file the bug report about not being able to override the default URL for
the GitHub repo

Again, thank you.

**Comment by TheBigBear** [comment]
@vernondcole that is interesting? I am using my own github repo as the default in my setup, with no issue, do you mind showing me your report that was 'swept under the carpet'?

**Pull request merged**
