### PR TITLE
Adds the url added to the nsclient++ installer version 0.4.3.143 as w…

### PR DESCRIPTION
**Pull request by ameneau-xetus**
…as done for saltstack/salt-winrepo#586

### CODE REVIEW

**Comment by ameneau-xetus** [comment]
Oh yikes! Thanks for catching that @TheBigBear! I've fixed it and rebased the branch, so it should be good to go!

**Comment by ameneau-xetus** [comment]
hmm... so, I just noticed something testing 32bit installers, the full_name is wrong (should be NSClient++ (x86) instead of NSClient++) and causes the state to fail.

In addition, the link for version 0.3.9.328 is broken

I'll update this to resolve both of those issues unless you (@TheBigBear) recommend having the fixes happen separately

**Comment by TheBigBear** [comment]
No, thats ok, to fix two issues on same package in one PR. Thanks.

**Comment by ameneau-xetus** [comment]
Thanks again for the comments! it should be good to go now

**Pull request merged**
