### PR TITLE
sls for New Relic Infrastructure

### PR DESCRIPTION
**Pull request by nmb88**

### CODE REVIEW

**Comment by danielcb** [comment]
I would propose to not use latest, but use the real versions to allow deinstallation etc..
E.g. something like this (not tested):

```
newrelic-infra:
   {% for version in ['1.0.279', '1.0.292', '1.0.296', '1.0.301', '1.0.311', '1.0.316', '1.0.323', '1.0.336', '1.0.338', '1.0.341', '1.0.673', '1.0.677', '1.0.682', '1.0.690', '1.0.703'] %}
  '{{ version }}':
    full_name: 'New Relic Infrastructure Agent'
    installer: 'https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.{{ version }}.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.{{ version }}.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  {% endfor %}
```

**Comment by nmb88** [comment]
Thank you!  I assumed there weren't past versions available (I obviously didn't look very hard).

**Comment by TheBigBear** [comment]
@nmb last I checked winrepo-ng was not able to properly handle and detect installations if the full_name did not change between versions. So in the past one had to restrict it to the latest version in the sls file for it to work. That was quite a while ago, maybe you have tested this and know that you can now install and upgrade etc as you' expect?

**Comment by danielcb** [comment]
@nmb88 did you test it locally for syntax errors and the behavior TheBigBear is describing? E.g. by installing two versions?

**Comment by nmb88** [comment]
I did test it.  It seems to upgrade just fine, but it can't downgrade without doing a `pkg.remove` first (I'm not sure if that's even supported anyway).

Here's all my testing:
```
root@saltmaster:/vagrant/# cat saltstack/salt/win/repo-ng/salt-winrepo-ng/newrelic-infra.sls 
newrelic-infra:
  {% for version in ['1.0.279', '1.0.292', '1.0.296', '1.0.301', '1.0.311', '1.0.316', '1.0.323', '1.0.336', '1.0.338', '1.0.341', '1.0.673', '1.0.677', '1.0.682', '1.0.690', '1.0.703'] %}
 '{{ version }}':
   full_name: 'New Relic Infrastructure Agent'
   installer: 'https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.{{ version }}.msi'
   install_flags: '/qn /norestart'
   uninstaller: 'https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.{{ version }}.msi'
   uninstall_flags: '/qn /norestart'
   msiexec: True
   locale: en_US
   reboot: False
 {% endfor %}
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.refresh_db
nick-test-win:
    ----------
    failed:
        0
    success:
        236
    total:
        236
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.703
        old:
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.remove newrelic-infra
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
        old:
            1.0.703
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.323'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.323
        old:
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.703
        old:
            1.0.323
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.292'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        install status:
            failed
ERROR: Minions returned with non-zero exit code
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.remove newrelic-infra
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
        old:
            1.0.703
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.292'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.292
        old:
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.323'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.323
        old:
            1.0.292
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.292'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        install status:
            failed
ERROR: Minions returned with non-zero exit code
root@saltmaster:/vagrant/# salt -G 'os:windows' pkg.install newrelic-infra version='1.0.703'
nick-test-win:
    ----------
    newrelic-infra:
        ----------
        new:
            1.0.703
        old:
            1.0.323
```

**Comment by danielcb** [comment]
Thanks! Looks good to me. @TheBigBear?

**Comment by nmb88** [comment]
@danielcb @TheBigBear Will this be merged?

**Pull request merged**
