### PR TITLE
Update LibreOffice version to 5.2.7.2

### PR DESCRIPTION
**Pull request by akoscomp**
I update version to last Still version.

### CODE REVIEW

**Comment by danielcb** [comment]
I think it would be better to add a new version and not change/overwrite a already used version. I'm not sure how states behave, if they use the version you just deleted. @TheBigBear ?

**Comment by akoscomp** [comment]
The updated/deleted version was 5.2.4, and 5.2.7 is a minor update for it, only security and stability issues.
LibreOffice have two active type of installers:
Still (now 5.2.7) - a stable, version, recommended for everyone
Fresh (now 5.3.3) - a new version, is stable, released, but recommended for early adopters and new function testers. In 4-6 weeks this will become a Still version, and the support for 5.2.x will be end.

**Comment by danielcb** [comment]
I don't think anyone should use/stay at the old verison, I'm just not sure what happens if your state depends on a version that isn't available anymore in the repo.

**Comment by akoscomp** [comment]
Now I understand, what do you want. I'm new in salt, and I don't know that is important to keep the old version. I make a new SLS file, and please drop this request.

**Comment by danielcb** [comment]
Thanks for updating and sorry for the delay.

**Pull request merged**
