### PR TITLE
Testing for broken links using Travis

### PR DESCRIPTION
**Pull request by moebiuseye**
These continuous integration patterns should help keep all sls files up to date.

### CODE REVIEW

**Comment by TheBigBear** [comment]
@moebiuseye thank you so much for this. Really great and helpful addition, much appreciated.

**Comment by moebiuseye** [comment]
You're very welcome. 

As you can see here, this build is failing because a number of the links get a 404. https://travis-ci.org/moebiuseye/salt-winrepo-ng 

Also, feel free to add  the same files to other repos: they may or may not apply because I have not made tests.

**Comment by TheBigBear** [comment]
@moebiuseye ok, I have now set mine up, so my commits should not have any 404 anymore, will have to look at testing for some of the other frequent errors I have when doing commits to the saltstack winrepo and winrepo-ng repos

Can I have something like a once a day run over all the sls files in a repo? so I would catch 404 that develop as they happen? Or is this always strictly pull or commit based?

**Comment by TheBigBear** [comment]
@moebiuseye great I have now added this tomy own winrepo-ng and to winrepo and I have two questions.
on the winrepo it stops with:
https://travis-ci.org/TheBigBear/salt-winrepo
```
0.00s$ ./.travis/tests.py
/home/travis/build.sh: line 45: ./.travis/tests.py: Permission denied
```
any ideas? I used the same file and content as on winrepo-ng?

and second question, can I make it continue , so it gives me ALL the 404's that need fixing? 

or in some ways it woudl be nicer if it only tested the recently pushed or committed sls file, so I don't have to wait for a full repo check of 404 messages. Will this actually pull down the renote files at every commit? That would be a lot of bandwith and those sites might start to notice travis-ci IPs and strat blocking them? no?

**Comment by moebiuseye** [comment]
I've found this: https://docs.travis-ci.com/user/cron-jobs/ 

You should set the `test.py` file with executable bit (`chmod +x`) on linux. I think you should be able to set that bit with the files properties on windows.

**Comment by moebiuseye** [comment]
Because the script I made only makes HTTP HEAD requests, the file is not being downloaded, hence, there is no noticable bandwidth jump. 

Websites will not ban travis IPs, hopefully. 
HTTP HEAD requests only ask the server to inform the client wether or not the file is present, and may indicate if any other error has happened. For instance, Internal Server Errors will be caught by my script but will not trigger a build failure because this kind of errors are very likely to be temporary.

**Comment by moebiuseye** [comment]
You can make it continue, by editing the python code accordingly to your needs.

**Comment by TheBigBear** [comment]
@moebiuseye ok, thanks.  ( I have now gone through the entire winrepo-ng and winrepo repos and fixed every single 404 yay! Thank you so much. There were many! Way too many! )

BUT ...

Just now I have added a new package. duplicati 1.3.4 a simple msi from googlecode. (and despite travis-ci failing it - I have merged it into the saltstack winrepo-ng and winrepo repos. so you coudl test it from there) 

The strange thing is your travis-ci python 404 tests fail the URL
```
https://duplicati.googlecode.com/files/Duplicati%201.3.4.x64.msi
```

_BUT browers, wget, curl, AND winrepo-ng itself also pass it, just fine._

```in other words it is a false positive on travis-ci ??? Any idea ???```

Any idea? could you have a look if you figure out why travis-ci running your tests fails this URL?

Here is the output of wget, curl, winrepo-ng that works and then the output of travis-ci test that is failing?

wget has no issue whatsoever
``` 
wget https://duplicati.googlecode.com/files/Duplicati%201.3.4.x64.msi
--2016-05-14 18:37:38--  https://duplicati.googlecode.com/files/Duplicati%201.3.4.x64.msi
Resolving duplicati.googlecode.com... 64.233.184.82, 2a00:1450:400c:c0b::52
Connecting to duplicati.googlecode.com|64.233.184.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10008262 (9.5M) [Composite Document File V2 Document, corrupt: Can't read SAT]
Saving to: 'Duplicati 1.3.4.x64.msi'

Duplicati 1.3.4.x64.msi                        100%[=================================================================================================>]   9.54M  6.66MB/s    in 1.4s    

2016-05-14 18:37:40 (6.66 MB/s) - 'Duplicati 1.3.4.x64.msi' saved [10008262/10008262]
```
```
wget https://duplicati.googlecode.com/files/Duplicati%201.3.4.msi
--2016-05-14 18:37:46--  https://duplicati.googlecode.com/files/Duplicati%201.3.4.msi
Resolving duplicati.googlecode.com... 64.233.184.82, 2a00:1450:400c:c0b::52
Connecting to duplicati.googlecode.com|64.233.184.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10008254 (9.5M) [Composite Document File V2 Document, corrupt: Can't read SAT]
Saving to: 'Duplicati 1.3.4.msi'

Duplicati 1.3.4.msi                            100%[=================================================================================================>]   9.54M  6.37MB/s    in 1.5s    

2016-05-14 18:37:48 (6.37 MB/s) - 'Duplicati 1.3.4.msi' saved [10008254/10008254]
```

and also curl is fine

```
curl -o "Duplicati 1.3.4.msi"  https://duplicati.googlecode.com/files/Duplicati%201.3.4.msi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9773k  100 9773k    0     0  5306k      0  0:00:01  0:00:01 --:--:-- 5306k
curl -o "Duplicati 1.3.4.x64.msi"  https://duplicati.googlecode.com/files/Duplicati%201.3.4.x64.msi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9773k  100 9773k    0     0  5553k      0  0:00:01  0:00:01 --:--:-- 5553k
```

as is winrepo-ng, it also has no issue and downloads and installs duplicati 1.3.4 just fine.

```
C:\salt>salt-call pkg.install duplicati
[INFO    ] Executing command ['msiexec', '/i', '... <cut rest of line>
local:
    ----------
    duplicati:
        ----------
        new:
            1.3.4
        old:
```

BUT travis-ci using your .travis/tests.py fails? 

```
---( duplicati.sls )---
https://duplicati.googlecode.com/files/Duplicati%201.3.4.x64.msi
Traceback (most recent call last):
  File "./.travis/tests.py", line 46, in <module>
    process_each(data)
  File "./.travis/tests.py", line 26, in process_each
    assert C.getinfo(curl.HTTP_CODE) != 404, "[ERROR]\tURL returned code 404. File Missing? "
AssertionError: [ERROR]	URL returned code 404. File Missing?
```

PS: the URL has a space as '%20' in it, but so do loads of other winrepo sls installers, and travis-ci does not bark at them, so I don't think that's it.

**Comment by moebiuseye** [comment]
It is a false positive! I've tested with curl and it only fails when the request method is HEAD (it only fails when using the `--head` option).

**Comment by moebiuseye** [comment]
I can try and request the first 10 bytes of the files with a GET request when and only when the HEAD request fails. 

I'll be looking into that in a week: I've got my last exams very soon!

**Comment by TheBigBear** [comment]
@moebiuseye hi, hope your exams went well. 
I am not a python programer myself, hence I am helping the project in areas and with skills that I can do, which is looking after installers etc.
 
If you ever have the time to code up the above then I would be very grateful as would probably others if they knew how much this automatic CI can help in all of this.

**Comment by moebiuseye** [comment]
I'm trying something right now. 
Exams are going well, thank you. :) 
This thread might be read by an examinator, because I'm relying on this to illustrate contrinuous integration. 

I'll make a new pull request for this very soon.

**Pull request merged**
