### PR TITLE
Fix broken URL, make it easier to add new

### PR DESCRIPTION
**Pull request by twangboy**
https://github.com/saltstack/salt-winrepo-ng/issues/1712

### CODE REVIEW

**Comment by twangboy** [comment]
@dafyddj Need to figure out how to get the url checker to follow these URLs

**Comment by dafyddj** [comment]
I will take a look and see what I can do.

**Comment by TheBigBear** [comment]
@twangboy fosshub have added a number of protections against automatic downloading. But the most recent version can usually be found on the fossies site. So you could move the older versions to be there with the URL check disabled and no installers anymore and have only the lates version of classic shell in place via fossils download . will do a PR in a minute. Stumbled across this as I was trying to update audacity and they have moved to fosshub, whose URLs all fails the URL test. Checked on chocolatey.org about audacity and fond the fossies workaround.

**Comment by TheBigBear** [comment]
@twangboy I have submitted a PR to your personal GH repos patch for this. If you merge that it should work.

**Comment by twangboy** [comment]
Sorry @TheBigBear I just saw your PR. Just merged it. Let's see if that fixes this.

**Pull request merged**
