### PR TITLE
Create initial intellij

### PR DESCRIPTION
**Pull request by TheBigBear**
Based on commit https://github.com/saltstack/salt-winrepo/commit/26d70cf466d069d62f90a3a2be05ba957af25f95 by @DavidJFelix

### CODE REVIEW

**Comment by DavidJFelix** [comment]
Let me in on the secret. What is salt-winrepo-ng? Should I be sending my PRs here?

**Comment by TheBigBear** [comment]
@DavidJFelix what secret? ;-)

The imminent Berryllium rel. (2015.8.x) will allow for jinja2 templated winrepo sls files.

__BUT__ any windows salt minions  <2015.8 will break, hence a new winrepo was created -> winrepo-ng.

Have a peek at the 'new' vagrant sls file under winrepo-ng https://github.com/saltstack/salt-winrepo-ng/blob/master/vagrant.sls .

So, for now we appreciate the winrepo sls files to be created in the "old" winrep (more typing for you - and less typing for me) and we'll create the "new" templated ones from that.

**Comment by DavidJFelix** [comment]
Oh neat. I just assumed winrepo was handled like formulas and this was already allowed.

**Comment by DavidJFelix** [comment]
one more question @TheBigBear, what's the deal with the msi uninstallers with UUIDs in the field name. Like: https://github.com/saltstack/salt-winrepo-ng/blob/master/virtualbox.sls#L7

How are you getting that number?

**Pull request merged**
