### PR TITLE
added queue explorer pro

### PR DESCRIPTION
**Pull request by kaluznyt**

### CODE REVIEW

**Comment by TheBigBear** [comment]
@kaluznyt this sls seems to assume a 64 bit OS install? ( hard coded x86 program files folder for uninstall )

Please re-write using jinja to help do the right thing regardless of 32 bit or 64 bit windows install.

**Comment by kaluznyt** [comment]
Actually I think there is only 32 bit version of the software

**Comment by TheBigBear** [comment]
that may be the case, but if installed on a 32 bit windows the uninstaller in your sls will fail. 

so you have to always write for both, copy from another sls that is already done right.

**Comment by kaluznyt** [comment]
should be fine now ?

**Comment by TheBigBear** [comment]
@kaluznyt thanks for your PR

**Pull request merged**
