### PR TITLE
Update openvpn.sls to ver. 2.4.10

### PR DESCRIPTION
**Pull request by TheBigBear**
this needs a couple more upgrades to 2.5.x but for that I first need to get on top of Jinja macros to add a new template to be used for the new msi installer they switched to from the old standard exe @dafyddj or @twangboy can you help me improve or add this msi installer section for 2.5.0 - 2.5.1 ? in PR https://github.com/saltstack/salt-winrepo-ng/pull/1818

### CODE REVIEW

**Comment by TheBigBear** [comment]
@dafyddj any idea why the pre-commit URL checks all fail to for openvpn? did they use to work lat year when you added 4.8.x and 4.9.x ?

**Comment by dafyddj** [comment]
I'm quite happy to take a look at this @TheBigBear as it's a package I rely on.
I will need to look into what has happened to the URL checks but as you can see many changes have happened since then.

PS thanks for your recent work. It's good to see some renewed energy for this repo.

**Comment by TheBigBear** [comment]
@dafyddj cool, thanks. BTW FYI, I also already have a WIP PR open for adding the msi installer in the jinja macro. Thought it best to keep the updating to latest 2.4.x 2.4.10 in this PR  and deal with the jinja macro expansion and adding msi installer in a separate PR https://github.com/saltstack/salt-winrepo-ng/pull/1818

**Comment by TheBigBear** [comment]
All the tests are failing, BUT the installer works. This is a pre-commit URL test failure. 403 errors are redirects and work and is the way openvpn make their downloads available. I have a issue here [here 1835](https://github.com/saltstack/salt-winrepo-ng/issues/1835) to fix the pre-commit URL checker to cope better with 403 URLs

**Review by twangboy — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
