### PR TITLE
Nmap version update 7.01

### PR DESCRIPTION
**Pull request by gqgunhed**
- Updated version
- combined into for-loop
- Fixed typo in uninstaller

### CODE REVIEW

**Comment by TheBigBear** [comment]
@gqgunhed have you tested this? 
In the past the nmap installer did NOT set the version number in the DisplayVersion field in the uninstaller key in the registry, and consequently the winrepo installer only ever found version "Not Found", which makes it impossible to have a sls file for more than one version that actually works.
The 'best' workaround in this case is probably to always have the winrepo installer sls file only ever point to the latest released version of nmap instead.

**Comment by gqgunhed** [comment]
@TheBigBear I tested installing by pkg.install and removing with pkg.purge (without specific version). As far as I remember it is possible that it showed only "Not Found" as "old:" at the time of removing.
So maybe it's better to keep only the latest version in the file.
You have by far more experience with those installers than me :-)

**Comment by gqgunhed** [comment]
@TheBigBear so should I edit the nmap sls to only include the latest version?

**Comment by TheBigBear** [comment]
Yes, please do, I just double checked, and even the most up-to-date version of the 7.x series of nmap still does not set the windows unistall "DisplayVersion" registry key as it should.

nmap-7 x-no-windows-registry-uninstall-displayversion-set

**Comment by TheBigBear** [comment]
have added upstream PR on nmap project 
https://github.com/nmap/nmap/pull/263

**Comment by gqgunhed** [comment]
very cool :-) I used the old 6.47 sls and just replaced 6.47 with 7.01.

**Comment by TheBigBear** [comment]
@gqgunhed thanks. and once the upstream nmap windows installer has added the version number we can then add a few versions into a 'for' loop, as planned.

**Pull request merged**
