### PR TITLE
Create mariadb.sls

### PR DESCRIPTION
**Pull request by scheste**
Initial version of MariaDB

### CODE REVIEW

**Comment by scheste** [comment]
I don't know why the check fails, I can download and install mariadb from my test environment with salt 2018.3.3.

**Comment by scheste** [comment]
I have successfully installed and uninstalled all listed versions. Maybe it`s also due to the default mirror, that this only allows a certain number of downloads...

**Comment by twangboy** [comment]
@TheBigBear Would you have any idea why these tests are failing?

**Comment by scheste** [comment]
Changing the default mirror did not work for the Travis CI test, on my test system I can install and remove mariadb without any problems.

salt 'win2019' pkg.install mariadb
win2019:
    ----------
    mariadb:
        ----------
        new:
            10.3.13.0
        old:

salt 'win2019' pkg.remove mariadb
win2019:
    ----------
    mariadb:
        ----------
        new:
        old:
            10.3.13.0

**Comment by twangboy** [comment]
@stratusjerry Any ideas why tests are failing here?

**Comment by stratusjerry** [comment]
> @stratusjerry Any ideas why tests are failing here?

@twangboy Yes, it looks like that URL requires a mirrored repo to be appended to the end, which acts as a redirect to that mirror. Of note, not all mirrors have all packages. Based off the original file, I have created #1579 which uses a different URL that seems to work.

**Comment by twangboy** [comment]
Closed in favor of https://github.com/saltstack/salt-winrepo-ng/pull/1579

**Pull request closed without merging**
