### PR TITLE
check_mk_agent 1.2.8p26

### PR DESCRIPTION
**Pull request by gurubert**
new version for check_mk_agent

### CODE REVIEW

**Comment by gurubert** [comment]
Now with 1.4.0p15, too.

**Comment by TheBigBear** [comment]
@gurubert the numbers are still not sorted left to right in most recent to older? you going to re-shuffle ...?

**Comment by gurubert** [comment]
I must have missed @twangboy's comment from October. Now numbers are in reverse order.

**Comment by TheBigBear** [comment]
@twangboy LGTM @gurubert has done as you asked, so I am now merging this.

**Pull request merged**
