### PR TITLE
Microsoft build tools

### PR DESCRIPTION
**Pull request by Cryowatt**
Adding Microsoft Build Tool 2015
- For msbuild support

### CODE REVIEW

**Comment by TheBigBear** [comment]
@Cryowatt thanks for this. Are you sure they use a single installer to install either the 64 bit or 32 bit build tools? In every other product they have two different installers, one for 32 bit and one for 64 bit? Can you please double check and confirm, before I merge this?

**Comment by TheBigBear** [comment]
@Cryowatt can you please also make the install flag match all other msi installers and use /qn and /norestart , please? Thanks.

**Comment by Cryowatt** [comment]
Yeah, the installer is a bit weird. It actually installs both the 32-bit and 64-bit versions but they seem to be tied together. 64-bit OSes get both installed but they are removed in one shot. This configuration seemed to make the most sense to me.

**Comment by Cryowatt** [comment]
I updated the installer flags.\

**Comment by TheBigBear** [comment]
@Cryowatt, ok, thanks for double checking. Never seen this before from MS, but take your word for it. Thanks for adding this sls file.

**Pull request merged**
