### PR TITLE
big catch up with upstream master on branch Travis ci cron daily

### PR DESCRIPTION
**Pull request by TheBigBear**

### CODE REVIEW

**Comment by twangboy** [comment]
@TheBigBear Can we merge with the tests failing?

**Comment by TheBigBear** [comment]
@twangboy yes, we can, it only affects me, and those travis tests don't do the trick anyway. I should really work on removing them.

**Comment by twangboy** [comment]
@TheBigBear I think the travis tests do a pretty good job catching bad URL's...

**Comment by TheBigBear** [comment]
@twangboy yes, it does indeed. how can I remove just the failing items and have the rest update ?

**Comment by TheBigBear** [comment]
@twangboy - actually I just looked down the list. And I don't have the time to do this, so I am now abandoning this PR - which is of course fine - but it means that you will have an ever increasing amount of travis-ci tests that will keep failing ....

**Comment by twangboy** [comment]
We've got a lot of links to fix...

**Pull request closed without merging**
